---
- name: Install the .bashrc
  copy:
      src: .bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

# Install needed packages
- name: Install dev packages
  dnf:
      name:
      - git
      - docker
      - docker-compose
      - mysql
      - mysql-server
      - httpie
      - python3-pip
      - python3-requests
      - python3-pytz
      - python3-swiftclient
      - python3-coverage
      - python3-mod_wsgi
      - python3-pudb
      - libcurl-devel
      - openssl-devel
      - gcc
      - python3-pycurl
      - make
      - expat-devel
      - libgcc
      - redhat-rpm-config
      - python3-devel
      - python3-mysql
      - community-mysql-devel
      state: present

- name: pip3 install python-chrisstoreclient
  pip:
      name: python-chrisstoreclient
      executable: pip3

- name: pip3 install django-filter
  pip:
      name: django-filter
      executable: pip3

- name: pip3 install django-storage-swift
  pip:
      name: django-storage-swift
      executable: pip3

- name: pip3 install django-cors-middleware
  pip:
      name: django-cors-middleware
      executable: pip3

- name: pip3 install django-djangorestframework
  pip:
      name: djangorestframework
      executable: pip3

- name: pip3 install django-debug-toolbar
  pip:
      name: django-debug-toolbar
      executable: pip3

- name: pip3 install django-extensions
  pip:
      name: django-extensions
      executable: pip3

- name: pip3 install collection-json
  pip:
      name: collection-json
      executable: pip3

- name: pip3 install pfurl
  pip:
      name: pfurl
      executable: pip3

- name: pip3 install pfmisc
  pip:
      name: pfmisc
      executable: pip3

- name: pip3 install docker
  pip:
      name: docker
      executable: pip3

- name: pip3 install mod-wsgi-httpd
  pip:
      name: mod-wsgi-httpd
      executable: pip3

- name: pip3 install venv
  pip:
      name: virtualenv
      executable: pip3

- name: pip3 install venvwrapper
  pip:
      name: virtualenvwrapper
      executable: pip3

- name: Install the .vimrc
  copy:
      src: .vimrc
      dest: /home/vagrant/.vimrc
      mode: 0644
      owner: vagrant
      group: vagrant

- name: Install the motd
  copy:
      src: motd
      dest: /etc/motd
      mode: 0644

- name: Create directory for repos
  file: 
      path: /home/vagrant/Repositories 
      state: directory
      mode: 0755

- name: Create directory for ChRIS
  file: 
      path: /home/vagrant/Repositories/ChRIS_ultron_backEnd
      state: directory
      mode: 0755

- name: Clone ChRIS repo
  git:
    repo: 'https://github.com/FNNDSC/ChRIS_ultron_backEnd.git' 
    dest: /home/vagrant/Repositories/ChRIS_ultron_backEnd
    update: yes

- name: Install python virtual environment
  environment:
    PYCURL_SSL_LIBRARY: openssl
  pip:
    requirements: /home/vagrant/Repositories/ChRIS_ultron_backEnd/requirements/local.txt
    virtualenv: /home/vagrant/chris_env
    virtualenv_command: /usr/bin/python3.6 -m venv
